name: update fuel price

on:
 schedule:
  - cron: "*/10 * * * *"
 workflow_dispatch:

jobs:
 update:

  runs-on: ubuntu-latest

  steps:

  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install packages
    run: npm install

  - name: Install browser
    run: npx playwright install chromium

  - name: Update price
    run: node update_price.js

  - name: Commit
    run: |
      git config --global user.name "github-actions"
      git config --global user.email "actions@github.com"
      git add price.json
      git commit -m "update price" || echo "no change"
      git push
